runtime: python27
api_version: 1
threadsafe: true

error_handlers:
  - file: dist/kirill/index.html

handlers:
  - url: /
    static_files: dist/kirill/index.html
    upload: dist/kirill/index.html

  - url: /(.*\.(gif|png|jpg|ico|bmp|css|otf|eot|svg|ttf|woff|js|txt|woff2))
    static_files: dist/kirill/\1
    upload: dist/kirill/(.*\.(gif|png|jpg|ico|bmp|css|otf|eot|svg|ttf|woff|js|txt|woff2))

  - url: /.*
    static_files: dist/kirill/index.html
    upload: dist/kirill/index.html

skip_files:
  - e2e/
  - node_modules/
  - src/
  - .idea/
  - .git/
