steps:
  - name: node
    entrypoint: npm
    args: ['install']
  - name: 'gcr.io/$PROJECT_ID/ng'
    args: ['run', 'kirill:prerender']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']
    timeout: '1600s'
timeout: '1601s'
